### ISSUE TITLE
Create README.md with TODO specification

### ISSUE THREAD

**Issue by ChShersh** [StasyaGera/todo-cli#1]
This README should cover the following thing:

- [x] Structure of TODO object (what fields typical TODO item should have)
- [x] States of TODO item. I propose: TODO, DONE, FAIL (for CANCELED, just want to have 4 letters for word; maybe you can find better name)
- [x] Operations with todo items.
