### ISSUE TITLE
Implement pure functions to work with TODO items

### ISSUE THREAD

**Issue by ChShersh** [StasyaGera/todo-cli#4]
When all data types are implemented in #3, you need to create pure functions which modify your types.

Here I will write explicitly what functions need to be done. Something described in README is already done (because you have constructors and record fields). Something we don't care about for now (like change history, it's difficult):

- [ ] `create a new item`: not really needed, because you have `Todo` constructor. But it's handy to have `defTodo` function, which takes only non-empty fields as arguments and sets empty fields to empty values.
- [ ] `get a list of items marked as done`: this can be a function which takes `State`
- [ ] `get N items with highest priority`: :top: :100: 
- [ ] `get everything by a specific tag`: :top: :100: 
- [ ] `get list of all tags with the amount of issues on each`: :top: :100: 

`create / delete / edit tags`: this is a difficult one. So, you should have something like 
```haskell
data TodoDB = TodoDB [Todo] [Tag]
```
When you rename tag you also need to rename this tag in every `Todo` item. And you can't delete tag if there's some TODO where this tag is the only tag.

Also, you should think more carefully how all these functions will work with subtasks.

**Comment by StasyaGera** [comment]
Could you please explain to me how to understand `defTodo` function?
My `Todo` record has two fields declared as `Maybe` and a may-be-empty list of subtasks, so how am I supposed to describe all combinations of empty fields?

**Comment by ChShersh** [comment]
@StasyaGera Sure. Your `Todo` constructor has type:

```haskell
Todo :: State -> Title -> ... -> Maybe Deadline -> Maybe String -> Todo
```

So if you want to create `Todo` with deadline and description set to `Nothing` you need to pass `Nothing` to this constructor explicitly. I think it might be convenient to have function which just sets those fields (and probably not only those) to default values (`Nothing` in that case):

```haskell
defTodo :: Title -> ... -> Todo
defTodo .. = Todo { todoDeadline    = Nothing
                  , todoDescription = Nothing
                  , todoSubtasks    = []
                  , .. }
```
